apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
spec:
  hostNetwork: true
  containers:
    - name: kube-scheduler
      image: 'k8s.gcr.io/hyperkube:v1.11.2'
      command:
        - '/hyperkube'
      args:
        - 'scheduler'
        - '--master=127.0.0.1:8080'
      livenessProbe:
        httpGet:
          scheme: HTTP
          host: '127.0.0.1'
          port: 10251
          path: '/healthz'
        initialDelaySeconds: 15
        timeoutSeconds: 15